### ISSUE TITLE
PhpMessDetector not looking at build directory as $this->phpci->buildPath = '/'

### ISSUE THREAD

**Issue by lordelph** [Block8/PHPCI#603] opened 2014-09-21 11:11 UTC
My phpci.yml contains
<pre>
php_mess_detector:
        path: "site/src"
        allow_failures: true
</pre>

But when phpmd is executed inside executeCommand, I can see the path given to it is /site/src, rather than relative to the build directory, e.g. /var/www/phpci/PHPCI/build/project1-build25/site/src

That path is calculated by [PhpMessDetector ::getTargetPath](https://github.com/Block8/PHPCI/blob/master/PHPCI/Plugin/PhpMessDetector.php#L210), which tries to use $this->phpci->buildPath to get the build path - unfortunately, this is "/"

**Comment by abador** [comment] 2015-02-19 23:43
Have the same problem with current build. Has anyone managed to workaround through this?:)

**Comment by lordelph** [comment] 2015-02-22 11:43
I thought I'd give the latest version a try, and I still get bitten by this bug. As before, the second line here is resulting in the buildPath getting reset to '/'

     $this->buildPath = PHPCI_DIR . 'PHPCI/build/' . $this->build->getId() . '/';
     $this->build->currentBuildPath = $this->buildPath;

I dumped Builder.php using the Vulcan Logic Disassembler to see the PHP opcodes which get executed....

         line     #* E I O op                           fetch          ext  return  operands
        -------------------------------------------------------------------------------------
         291     0  E >   FETCH_CONSTANT                                   ~1      'PHPCI%5CPHPCI_DIR'
                 1        CONCAT                                           ~2      ~1, 'PHPCI%2Fbuild%2F'
                 2        FETCH_OBJ_R                                      $3      'build'
                 3        INIT_METHOD_CALL                                         $3, 'getId'
                 4        DO_FCALL_BY_NAME                              0  $5      
                 5        CONCAT                                           ~6      ~2, $5
                 6        CONCAT                                           ~7      ~6, '%2F'
                 7        ASSIGN_OBJ                                               'buildPath'
                 8        OP_DATA                                                  ~7
         292     9        FETCH_OBJ_R                                      $10     'buildPath'
                10        FETCH_OBJ_W                                      $8      'build'
                11        ASSIGN_OBJ                                               $8, 'currentBuildPath'
                12        OP_DATA                                                  $10

I think I was hoping something odd would leap out at me, but it looks OK. The problem must be in how the opcodes are executed. Maybe someone else will spot something there.

It seems like the location which stores the buildPath is shared with some other variables. Here's an example

    $this->buildPath = PHPCI_DIR . 'PHPCI/build/' . $this->build->getId() . '/';
    $copy= "altered".$this->buildPath; 
    //at this point, $this->buildPath is intact and $copy is the buildpath prefixed with 'altered'
    $this->build->currentBuildPath = $this->buildPath;
    //now $this->buildpath='/' and $copy='altered/'

That's crazy - $copy should be an entirely separate variable, but it's like it always interpolates that value of buildPath into it whenever its read? It's the same result if I do  `$copy= $this->buildPath."altered"; `

That's as far as I've got...I've never seen anything quite like this!

**Comment by lordelph** [comment] 2015-02-22 13:47
Couple of other other things I've tried:

* disabling the Zend opcache
* upgrading PHP from `5.5.9-1ubuntu4.6` (built: Feb 13 2015 19:17:11) to `5.6.6-1+deb.sury.org~trusty+1` (built: Feb 20 2015 11:22:10) 

Neither helped. I'd love to find the answer but I'm running out of ideas...

**Comment by lordelph** [comment] 2015-02-22 14:59
Just wanted to note that I've spent a few hours looking at that before I discovered the logging code now strips out the buildpath from output - see https://github.com/Block8/PHPCI/blob/master/PHPCI/Logging/BuildDBLogHandler.php#L53 - that can be pretty deceiving, I'd suggest that change be reverted.

**Comment by abador** [comment] 2015-02-22 15:02
I have the same problems.
Changing the code doesn't help.
Don't know what to make of it...:/

**Comment by lordelph** [comment] 2015-02-22 15:40
Unfortunately, I tried a lot of things before discovering the logging had changed, and found it was now working for me. All I can suggest is upgrading PHP - I'm running PHP 5.6.6 and it was on something like 5.5.9 when I was having the problem.

**Comment by abador** [comment] 2015-02-22 19:11
Upgraded to PHP 5.6.6-1~dotdeb.1 (cli) (built: Feb 20 2015 19:57:36) and the problem is still there:/

**Comment by dancryer** [comment] 2015-11-03 20:15
Closing this on the assumption it is fixed and/or no longer relevant by now. Feel free to reopen if this assumption is incorrect.

**Closed by dancryer** 2015-11-03 20:15 UTC
Labels: bug:new, component:builder, flag:requires-feedback, version:1.6-or-below
