### ISSUE TITLE
PHPCI site problem with dates in the news page

### ISSUE THREAD

**Issue by Juje** [Block8/PHPCI#1207] opened 2016-04-15 09:04 UTC
First of all I didn't know where to post this so here it goes.

The news page of PHPCI at https://www.phptesting.org/news is having an issue with dates.
On the news page itself all posts have a static date of "2015-11-06".
And on a single post all posts have a static date of "2016-04-15".

**Comment by dancryer** [comment] 2016-04-27 15:47
Thanks for letting us know - I'll make sure it gets fixed shortly. 👍 

Going to close this for now though as it's not a bug with PHPCI itself.

**Closed by dancryer** 2016-04-27 15:47 UTC
