### ISSUE TITLE
Can't clone project

### ISSUE THREAD

**Issue by mkody** [Block8/PHPCI#1147] opened 2015-12-21 09:48 UTC
Hello, I've installed PHPCI following the documentation and everything was working fine until I launched a first build. It went with the GitHub hook at first but I get the same manually.

The repository I'm tring to work with is https://github.com/mkody/miseenprod.today
I'm running PHPCI with the daemon and serving the website with nginx/1.9.9.
The SSH key is set in the `Deploy keys`'s part of the project
(edit) And it says `Last used within the last day`

And that's the only thing I get:
```
Clonage dans '/var/www/phpci/PHPCI/build/15'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Failed to clone remote git repository.
Exception: Could not create a working copy.
```

I've tried to change from "GitHub" to "Remote URL" instead on the project details, giving it the ssh or HTTP URL, no changes.
I see it creates without errors the files and the folder inside `/var/www/phpci/PHPCI/build/` (`15.key`, `15.sh` and `15/` for example).

Is there a way to know more precisely where's the problem?

**Comment by tvbeek** [comment] 2015-12-21 10:12
Can you clone any other project? It is possible that the server blocks the port for git to the outside

**Comment by mkody** [comment] 2015-12-21 10:24
I think I found where the problem is.
If you don't login with your GitHub account in the settings, the `Choose a GitHub repository` on the project details doesn't show up and pasting a GitHub URL was reduced to "user/repo". But I don't understand why the https url didn't work.

While trying with an other project, I got a different issue this time. Should I open a new ticket?
```
Clonage dans '/var/www/phpci/PHPCI/build/19'...

Working copy created: /
RUNNING PLUGIN: \PHPCI\Plugin\PhpDocblockChecker
Could not find phpdoccheck
PLUGIN: FAILED
RUNNING PLUGIN: \PHPCI\Plugin\Codeception
Exception: Warning: file_get_contents(/tests/_output/report.tap.log): failed to open stream: No such file or directory in /var/www/phpci/PHPCI/Plugin/Codeception.php line 94
PLUGIN: FAILED
RUNNING PLUGIN: \PHPCI\Plugin\PhpCodeSniffer
Could not find phpcs
PLUGIN: FAILED
RUNNING PLUGIN: \PHPCI\Plugin\PhpLoc
PLUGIN: SUCCESS
RUNNING PLUGIN: \PHPCI\Plugin\TechnicalDebt
Found  instances of TODO, FIXME, TO DO, FIX ME
PLUGIN: SUCCESS
RUNNING PLUGIN: \PHPCI\Plugin\PhpMessDetector
fatal: ambiguous argument 'Manual^!': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git  [...] -- [...]'

```

**Comment by olimorris** [comment] 2016-02-29 06:34
@mkody can you close this if the problem is sorted?

**Closed** 2016-03-14 21:13 UTC

**Comment by sancel22** [comment] 2016-04-12 10:14
@mkody I had the same problem. How did you solve this one?
